# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-04-21 21:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Terapia',
                'verbose_name_plural': 'Categorias de Terapias',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name': 'Publicación del Foro',
                'verbose_name_plural': 'Publicaciones del Foro',
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=150, verbose_name='Nombre')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('therapycount', models.IntegerField(verbose_name='Numero de Terapias')),
                ('wellbeing', models.IntegerField(verbose_name='Bienestar')),
                ('currentmood', models.CharField(max_length=150, verbose_name='Estado de Animo')),
                ('stresslevel', models.IntegerField(verbose_name='Nivel de Estres')),
                ('anxietylevel', models.IntegerField(verbose_name='Nivel de Ansiedad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('text', models.TextField(max_length=1000, verbose_name='Texto')),
                ('icon', models.ImageField(upload_to='therapy', verbose_name='Icono')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.Categories', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256, verbose_name='Descripcion')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('found', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.Categories', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Terapia',
                'verbose_name_plural': 'Terapias',
            },
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('thread_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('initial_post', models.TextField(max_length=1000, verbose_name='Mensaje Inicial')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Hilo del Foro',
                'verbose_name_plural': 'Hilos del Foro',
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='therapy.Threads', verbose_name='Hilo'),
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
